"wall_feng_l": "wall-feng-l"
"wall_feng_l__004": "wall-feng-l:004"
"wall_feng_r": "wall-feng-r"
"wall_inpipe": "wall-inpipe"
"wall_l": "wall-l"
"wall_outpipe_inner": "wall-outpipe-inner"
"wall_pipe_outter": "wall-pipe-outter"
"wall_pipe_top": "wall-pipe-top"
"wall_r": "wall-r"