title : "后处理报告参数内容汇总"
editor: "computer auto writer"
checker: "高建秋"
auth: "高建秋"
promts : "\n\n2.中国科学院理化技术研究所不提供任何明示、暗示或法定担保，包括但不限于对适销性或特定用途适用性的任何保证，对报告内容无误的任何保证。在任何情况下，中国科学院理化技术研究所均不得对任何损害承担任何责任，包括但不限于因使用本报告而产生的直接、间接、特殊或后果性损害，无论是否基于担保、商业协议、侵权行为或其他原因；无论伤害是否由人员、财产或其他原因造成；以及损失是否由物品或中国科学院理化技术研究所可能提供的任何服务的结果造成或产生。"
